#!/bin/sh

git submodule update --init --recursive
docker run --rm -it -v $(realpath src):/capslock-tools -w /capslock-tools --entrypoint "" capslock \
    /bin/sh -c '(cd qemu && sh /scripts/build/qemu.sh); (cd llvm && sh /scripts/build/llvm.sh); (cd rust && sh /scripts/build/rust.sh)'
