language: rust
cache: cargo
rust:
    - 1.31.0 # The first one with rust 2018
    - 1.45.0 # The weak-into-raw feature stabilized
    - stable
    - beta
    - nightly
os:
    - linux
    - osx

before_script:
    - |
      (travis_wait rustup component add rustfmt-preview || true) &&
      (test "$TRAVIS_RUST_VERSION" == 1.31.0 || travis_wait rustup component add clippy-preview || true)

script:
    ./ci-check.sh
